# Generated by Django 5.1.2 on 2024-10-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="context",
            new_name="content",
        ),
    ]
